### ISSUE TITLE
Build problem on legacy-closure-lib

### ISSUE THREAD

**Issue by loicbourg** [mxmul/closure-loader#11]
Hi,

I'm having problem trying to make work the legacy-closure-lib example, I got the error:

```
ERROR in multi app
Module not found: Error: Cannot resolve module 'closure' in /tmp/closure-loader/examples/legacy-closure-lib
 @ multi app
```

when running the webpack build.

here are the steps i've done to produce the bug:
- git clone git@github.com:eXaminator/closure-loader.git
- cd closure-loader/
- npm install
- cd examples/legacy-closure-lib/
- npm install
- npm start

npm version: 3.7.5

**Comment by eXaminator** [comment]
The problem should be fixed. I missed this example when updating the webpack configs a while ago. The examples use a relative path to the closure loader. I fixed this example now and it should work as expected.
