### ISSUE TITLE
Webpack peer dependecy version

### ISSUE THREAD

**Issue by petrleocompel** [mxmul/closure-loader#25]
I think there is no need to lock on Webpack v1. It works on Webpack v2 (Tested with 2.4.1)
Please allow as peer dependency Webpack v2 also.

**Comment by eXaminator** [comment]
I will do a quick test (and maybe create an example) myself and change it if I don't run into any problems. Should be in the next update.

**Comment by eXaminator** [comment]
Version 0.3.0 should now be webpack2 compatible

**Comment by petrleocompel** [comment]
:+1: Thanks guy. By this closure-loader i was able to convert 5 year old project without npm and manual script compiling to Webpack and npm dependencies. :slightly_smiling_face:

**Comment by eXaminator** [comment]
That's what I created it for, good luck with your project :)
