### ISSUE TITLE
shimming for closure library - goog.global

### ISSUE THREAD

**Issue by deej81** [mxmul/closure-loader#30]
This is only an issue with the examples not the loader itself.

When importing some modules from closure library (the rich text editor in particular) you end up with issues caused by the fact that when loading the base.js file the this argument is not the window object it is expecting.

It seems the goog.global is built on top of the window object and in many modules such as [labs/useragent/util](https://github.com/google/closure-library/blob/666f6eca9316d7bbc56433a524e340b2cd8572a7/closure/goog/labs/useragent/util.js#L54) rely on that fact for access to window properties such as "navigator"

using the shim shown in the examples these properties and methods are missing which obviously causes subtle bugs. The only way I've found so far to solve this looks seriously ugly; when loading the base file in webpack I've modified the imports section.

`"imports-loader?this=>function() { window['goog'] = window['goog'] ? window['goog'] : {}; return window; }()&goog=>this.goog"`

I think it's just my lack of understanding of how the mechanics of this all work, would really appreciate any thoughts on what I'm doing wrong?

**Comment by eXaminator** [comment]
Your solution looks ok, but you could also try `imports?this=>window&goog=>this.goog`. Sadly I have no idea why I didn't set this to the window object, but the examples I tested worked. Please let me know if you encounter any problems with this solution. If not I'll change it in the examples.

**Comment by deej81** [comment]
Thanks I did try that solution, there's something subtle about the way base.js works that stops this from working though. Certainly my code failed to find the goog.inherits method.
