### ISSUE TITLE
This package is no longer maintained

### ISSUE THREAD

**Issue by eXaminator** [mxmul/closure-loader#38]
I will no longer maintain this package as I don't have enough time and I don't use it anymore myself.

If anyone wants to take over just get in touch.

**Comment by mxmul** [comment]
Hi! I'm definitely interested in taking over the project -- we've been using (a fork of) this package pretty extensively for the last few months :)

**Comment by eXaminator** [comment]
I added you as collaborator to the npm package. I think it would be best to simply use your fork from now on, what do you think? (there are't many issues and no open PRs that would suggest a transfer of this repo I think).

 I would simply add a note to the readme of this repo and would like to see a short mention of me (or rather this repo) in your readme. Would that be ok with you?

I saw that you experimented with tests on your fork, something I sadly never got around to and I would love to see it find its way to master in the future :)

**Comment by mxmul** [comment]
That would work, but I'd prefer to actually transfer the repo if possible. It'd preserve the existing issues/PR/stars and would set up a handy redirect from this url.

I'd be happy to credit you in the README :)

**Comment by eXaminator** [comment]
Ok, no problem. I'll look into it. :)

But you'll have to delete / rename your fork first. Otherwise it won't work.

**Comment by mxmul** [comment]
Thanks! I've removed my fork
