### ISSUE TITLE
Webpack 4 Support

### ISSUE THREAD

**Issue by Brian-Kaplan** [mxmul/closure-loader#39]
Just wondering if you've tested this loader with webpack 4? I'm having some issues myself.

**Comment by mxmul** [comment]
@Brian-Kaplan I haven't looked into Webpack 4 support yet, but I'm not surprised that it's not working. I can take a look.

**Comment by Brian-Kaplan** [comment]
Thanks @mxmul let me know what you come up with!

**Comment by mxmul** [comment]
@Brian-Kaplan closure-loader@0.9.0 should work with Webpack 4 (the test suite is now running on v4.5.0)! Let me know if you encounter any problems with it
