### ISSUE TITLE
Causes "Uncaught TypeError: Cannot set property '???' of undefined" in some cases.

### ISSUE THREAD

**Issue by occar421** [mxmul/closure-loader#41]
Hi, thank you for this loader 😄

I recently found the problem on this loader when I tried this loader to solve the dependency.  
In some cases, it causes "Uncaught TypeError: Cannot set property '???' of undefined".  
I assume it has bug during the empty object generation from this loader.

In '2.js' in demo...

<img width="494" alt="1" src="https://user-images.githubusercontent.com/3390557/40310144-ccdc5618-5d46-11e8-93ef-a71545a1c7fc.png">

<img width="479" alt="2" src="https://user-images.githubusercontent.com/3390557/40310153-d28af1f0-5d46-11e8-9520-0d9fd29ac30f.png">

↑ `a.b.c.g` is prepared.

　
<img width="477" alt="3" src="https://user-images.githubusercontent.com/3390557/40310154-d2b1471a-5d46-11e8-974c-f66514ae285e.png">

↑ `a.b.c.d` is erased!

　
<img width="476" alt="4" src="https://user-images.githubusercontent.com/3390557/40310155-d2db7274-5d46-11e8-9add-1011468fdc0c.png">

Then, `a.b.c.g.bar = function () {/* ... */}` causes error becuase `a.b.c.g` is not defined anymore.

(Windows 10, Chrome 66)

I confirmed that it runs well on the bundled js file generated by Google's Closure Compiler.

Demo: https://github.com/occar421/demo-for-issue/tree/master/closure-loader--1
(This is not minimum but enough to show the problem.)
You can see the difference of the behavior between `yarn start` (closure-loader) and `yarn build` + `yarn run serve` (google-closure-compiler) on 'public/index.html'.

Regards.

**Comment by mxmul** [comment]
@occar421 thanks for the bug report (and especially the reproducible demo)! Would you be interested in contributing a fix (or a failing test case)?

**Comment by occar421** [comment]
At least, I can make a failing test case.
I hope I can also fix 'lib/export-path.js' without any problem, but I afraid that it could cause a bad side effect to the current user.

Anyway, I assume it takes a week to send a completed PR from me (due to the work 👨‍💻).

**Comment by mxmul** [comment]
Merged #42 to fix this. Thanks again!
