### ISSUE TITLE
deep-extend 0.5.1 vulnerability

### ISSUE THREAD

**Issue by Brian-Kaplan** [mxmul/closure-loader#43]
The deep-extend version you ask for has a known vulnerability. Please update it to the latest.

See the discussion here for more details
https://github.com/unclechu/node-deep-extend/issues/41#issuecomment-391090870

Thanks

**Comment by rob-orr** [comment]
I would also like to see this resolved.

**Comment by mxmul** [comment]
Thanks for reporting! I upgraded most of this library's dependencies, and `npm audit` is now coming up clean :)
