### ISSUE TITLE
Cannot read property 'config' of null

### ISSUE THREAD

**Issue by Brian-Kaplan** [mxmul/closure-loader#45]
Having some issues with closure-loader 0.9.1. I'm trying to run some tests with karma and it looks like this call (line 216 in index.js) always returns a null object for my tests. Any ideas?

```
    const options = loaderUtils.getOptions(this);
```
This options object is asked for a config value later in that code and since options is null it crashes out.

Versions:
```
webpack: 4.10.2
closure-loader: 0.9.1
google-closure-library: v20160911.0.0
karma-webpack: 3.0.0
```

Thanks!

**Comment by Brian-Kaplan** [comment]
Looks like this happens if you provide no options to the loader... seems super obvious to me now. Not sure why the loader expects options to be defined though. Is that the intended behavior?

**Comment by mxmul** [comment]
@Brian-Kaplan Thanks for reporting! This is definitely a bug.

Happy to accept a PR if you'd like to fix this, otherwise I'll get to this sometime next week.
